# Generated by Django 5.2.3 on 2025-07-12 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('books', '0005_bookbuy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookbuy',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='bookbuy',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookbuy',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Borrows', to='account.userlibraryaccount'),
        ),
    ]
