# Generated by Django 5.2.3 on 2025-07-12 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('books', '0006_alter_bookbuy_options_bookbuy_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookBuy',
            new_name='BorrowBook',
        ),
    ]
