# Generated by Django 5.2.3 on 2025-07-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_rename_bookbuy_borrowbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowbook',
            name='return_book',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
