# Generated by Django 5.2.3 on 2025-07-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_bookrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrating',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
