# Generated by Django 5.2.3 on 2025-07-13 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('books', '0010_bookrating_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrating',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_account', to='account.userlibraryaccount'),
        ),
    ]
