# Generated by Django 5.2.3 on 2025-07-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_bookrating_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='raings',
            new_name='ratings',
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
